{
	"id": "ALAS2PYTHON3.8-2024-015",
	"advisories": [
		{
			"content": {
				"id": "ALAS2PYTHON3.8-2024-015",
				"title": "Amazon Linux 2 - Python3.8 2.0 - ALAS2PYTHON3.8-2024-015: medium priority package update for python38-pip",
				"description": "Package updates are available for Amazon Linux 2 - Python3.8 that fix the following vulnerabilities:\nCVE-2024-3651:\n\tpython-idna: potential DoS via resource consumption via specially crafted inputs to idna.encode()\n",
				"severity": [
					{
						"type": "vendor",
						"source": "linux-security@amazon.com",
						"vendor": "medium"
					}
				],
				"references": [
					{
						"source": "linux-security@amazon.com",
						"url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-3651"
					},
					{
						"source": "linux-security@amazon.com",
						"url": "https://alas.aws.amazon.com/AL2/ALASPYTHON3.8-2024-015.html"
					}
				]
			},
			"ecosystems": [
				"amazon:2"
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2024-3651",
				"references": [
					{
						"source": "linux-security@amazon.com",
						"url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-3651"
					}
				]
			},
			"ecosystems": [
				"amazon:2"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "amazon:2",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"fix_status": {
							"class": "fixed"
						},
						"package": {
							"name": "python38-pip",
							"architectures": [
								"noarch"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:21.0.1-4.amzn2.0.3"
								}
							],
							"fixed": [
								"0:21.0.1-4.amzn2.0.3"
							]
						}
					}
				]
			}
		}
	],
	"data_source": {
		"id": "amazon",
		"raws": [
			"vuls-data-raw-amazon/2/extras/python3.8/2024/ALAS2PYTHON3.8-2024-015.json"
		]
	}
}
